### ISSUE TITLE
How can I use this plugin?

### ISSUE THREAD

**Issue by c0de-bender** [rixx/pretix-question-placeholders#4]
Hey @rixx, thanks a lot for writing this plugin! It sounds like a useful thing for us, but in fact after installing it I didn't find where and how to use this in Pretix. And as you said [here yourself](https://github.com/rixx/pretix-question-placeholders/issues/2), your README doesn't help with it either yet.

I could potentially figure out details myself, but I'd need a starting point. Could you give a very brief description what the plugin does and how to use it?
- Which emails can I use this in? Automatic emails? Emails send out manually? Scheduled emails?
- Which placeholders can I use?
- What's the rule system? Can I make sth like if-else blocks within the email text to send out different texts depending on a question answer?

I'd already be happy about a short description, or about a hint in which file in your plugin source code I could get this information from myself. Thanks!

**Comment by rixx** [comment]
As you said yourself: this is a duplicate issue.

**Comment by rixx** [comment]
FWIW this plugin is not compatible with current pretix; as you can see, the last update was nearly three years ago. I will probably archive this repository at the end of the year, as I have no reason to maintain this plugin further.

**Comment by c0de-bender** [comment]
> As you said yourself: this is a duplicate issue.

Jep, kind of. I wanted to ask in the other issue first, but then I thought if other people wonder the same, it might be easier for them to find this issue here with the different title.

> FWIW this plugin is not compatible with current pretix; as you can see, the last update was nearly three years ago. I will probably archive this repository at the end of the year, as I have no reason to maintain this plugin further.

Ok, that's a pity. Thanks for your quick reply nevertheless!

**Comment by rixx** [comment]
> Jep, kind of. I wanted to ask in the other issue first, but then I thought if other people wonder the same, it might be easier for them to find this issue here with the different title.

Sure, but issues are not questions – this isn't a support forum :)

> Ok, that's a pity. Thanks for your quick reply nevertheless!

Happy to merge PRs of course, or transfer ownership if you or anybody else wants to take this over. Getting this plugin to run again should be fairly trivial by switching to modern build methods.

**Comment by c0de-bender** [comment]
> > Jep, kind of. I wanted to ask in the other issue first, but then I thought if other people wonder the same, it might be easier for them to find this issue here with the different title.
> 
> Sure, but issues are not questions – this isn't a support forum :)

Yeah, true. I didn't see a Question section here in this GitHub repo. But you're right, I should have thought of just writing you an email – I overlooked that, sorry.
 
> Happy to merge PRs of course, or transfer ownership if you or anybody else wants to take this over. Getting this plugin to run again should be fairly trivial by switching to modern build methods.

Thanks for the offer! I'm not proficient enough in Python (yet) to be able to do this. I could get help, but the functionality of the plugin is not essential (although it would be nice) for us. So currently I'm out. If that changes, I might get back to your offer at some point.
